# set wd to git repo folder
setwd(".")
colnames <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
colclasses <- c("character", "character", "character", "character", "character", "character", "character", "character", "character")
data = read.table("./household_power_consumption.txt", sep=";", col.names = colnames, colClasses = colclasses,header=TRUE)
data$DateTime <- strptime(paste(data$Date,data$Time), "%d/%m/%Y %H:%M:%S")
data$Date2 <- strptime(data$Date, "%d/%m/%Y")
sub_data <- subset(data, Date2>="2007-02-01" & Date2<="2007-02-02")
par(mfrow=c(2,2))

png(file="plot4.png")
plot(x=sub_data$DateTime, y = as.numeric(sub_data$Global_active_power),type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(x=sub_data$DateTime, y = as.numeric(sub_data$Voltage),type="l",xlab="",ylab="Voltage")
plot(x=sub_data$DateTime, y = as.numeric(sub_data$Sub_metering_1),type="n",xlab="",ylab="Energy sub metering")
lines(x=sub_data$DateTime, y = as.numeric(sub_data$Sub_metering_1))
lines(x=sub_data$DateTime, y = as.numeric(sub_data$Sub_metering_2),col="red")
lines(x=sub_data$DateTime, y = as.numeric(sub_data$Sub_metering_3),col="blue")
legend("topright", pch="-", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(x=sub_data$DateTime, y = as.numeric(sub_data$Global_reactive_power),type="l",xlab="",ylab="Global_reactive_power")
dev.off()
